version: '3'

networks:
  overbookd_preprod-net-api:
  traefik-public:
    external: true

services:
  backend:
    container_name: overbookd_preprod_backend
    image: registry.gitlab.com/24-heures-insa/overbookd-mono/backend:pre-prod
    restart: always
    networks:
      - overbookd_preprod-net-api
      - traefik-public
    volumes:
      - ./data/preprod/images:/app/images
    environment:
      DOMAIN: ${PREPROD_OVERBOOKD_DOMAIN}
      DATABASE_URL: mongodb://${PREPROD_OVERBOOKD_DATABASE_USERNAME}:${PREPROD_OVERBOOKD_DATABASE_PASSWORD}@overbookd_preprod_mongo:27017/
      GMAIL_USER: ${PREPROD_OVERBOOKD_EMAIL_USER}
      GMAIL_PASS: ${PREPROD_OVERBOOKD_EMAIL_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.preprod-api.tls=true"
      - "traefik.http.routers.preprod-api.tls.certresolver=le"
      - "traefik.http.routers.preprod-api.entrypoints=websecure"
      - "traefik.http.services.preprod-api.loadbalancer.server.port=2424"
      - "traefik.http.routers.preprod-api.rule=(Host(`preprod.overbookd.${DOMAIN}`) && PathPrefix(`/api`))"
      - "com.centurylinklabs.watchtower.enable=true"

  mongodb:
    container_name: overbookd_preprod_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PREPROD_OVERBOOKD_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PREPROD_OVERBOOKD_DATABASE_PASSWORD}
    networks:
      - overbookd_preprod-net-api
    ports:
    - 27017:27017
    volumes:
      - ./data/preprod/mongo/db:/data/db
      - ./data/preprod/mongo/configdb:/data/configdb

  frontend:
    container_name: overbookd_preprod_frontend
    image: registry.gitlab.com/24-heures-insa/overbookd-mono/frontend:pre-prod
    restart: always
    environment:
      NODE_ENV: preprod
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.preprod-front.tls=true"
      - "traefik.http.routers.preprod-front.tls.certresolver=le"
      - "traefik.http.routers.preprod-front.entrypoints=websecure"
      - "traefik.http.services.preprod-front.loadbalancer.server.port=1234"
      - "traefik.http.routers.preprod-front.rule=Host(`preprod.overbookd.${DOMAIN}`)"
      - "com.centurylinklabs.watchtower.enable=true"

  # doc:
  #   image: registry.gitlab.com/24-heures-insa/overbookd/documentation
  #   restart: always
  #   networks:
  #     - traefik-public
  #   environment:
  #     SITE: overbookd-doc
  #     WEBSITE_NAME: Documentation
  #     TEMPLATE: classic
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.preprod-doc.entrypoints=websecure"
  #     - "traefik.http.services.preprod-doc.loadbalancer.server.port=3001"
  #     - "traefik.http.routers.preprod-doc.rule=Host(`overbookd.${DOMAIN}`) && PathPrefix(`/docs`)"
  #     - "traefik.http.routers.preprod-doc.tls=true"
  #     - "traefik.http.routers.preprod-doc.middlewares=doc-redirect"
  #     - "traefik.http.middlewares.preprod-doc-redirect.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
  #     - "traefik.http.middlewares.preprod-doc-redirect.redirectregex.replacement=https://$$1/docs"