license_scanning:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: never
  variables:
    LICENSE_FINDER_CLI_OPTS: "--aggregate_paths=frontend backend"

eslint-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: never

nodejs-scan-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: never

semgrep-sast:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: never

  
secret_detection:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: never
